version: 2.1

jobs:
  build:
    working_directory: ~/holistics
    docker:
      - image: cimg/ruby:2.7.4
    steps:
     - checkout
     - run:
        command: bundle install 
  test:
    working_directory: ~/holistics
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - checkout
      - run:
          command: bundle exec rspec

workflows:
  exercise1: 
    jobs:
      - build
      - test:
          requires:
            - build
